from .chess_analysis_prompts import (
    POSITION_ASSESSMENT_PROMPT,
    KING_SAFETY_PROMPT,
    TACTICAL_ANALYSIS_PROMPT,
    STRATEGIC_ANALYSIS_PROMPT,
    BEST_MOVE_PROMPT,
    COMBINED_ANALYSIS_PROMPT,
)
from .playground_prompts import TEST1
from .training_prompts import INPUT_PROMPT, OUTPUT_PROMPT

__all__ = [
    "POSITION_ASSESSMENT_PROMPT",
    "KING_SAFETY_PROMPT",
    "TACTICAL_ANALYSIS_PROMPT",
    "STRATEGIC_ANALYSIS_PROMPT",
    "BEST_MOVE_PROMPT",
    "COMBINED_ANALYSIS_PROMPT",
    "INPUT_PROMPT",
    "OUTPUT_PROMPT",
    "TEST1",
]
